# Site
NEXT_PUBLIC_SITE_URL=https://lady-fabrics.com

# Sanity
NEXT_PUBLIC_SANITY_PROJECT_ID=
NEXT_PUBLIC_SANITY_DATASET=production
NEXT_PUBLIC_SANITY_API_VERSION=2024-10-01
SANITY_API_READ_TOKEN=
SANITY_API_WRITE_TOKEN=
SANITY_WEBHOOK_SECRET=

# Supabase
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_PROJECT_ID=

# Admin
ADMIN_EMAIL_ALLOWLIST=

# AI (Anthropic)
ANTHROPIC_API_KEY=

# Email (Resend)
RESEND_API_KEY=
NOTIFICATION_EMAIL=
